### PR TITLE
added score_only function and made compatible with cache

### PR DESCRIPTION
**Pull request by kirefu**
Updated file for Snakefile compatibility.

Best wishes,

Faheem

### CODE REVIEW

**Comment by mbanon** [comment]
Hey @kirefu ,
is it OK for you if I reject this pull request but I add the feature in Bicleaner 0.12, that will replace current version next week?
https://github.com/bitextor/bicleaner/tree/bicleaner-0.12

**Comment by kirefu** [comment]
Sure. Let me know if you want me to submit another pull request after the current version is replaced, or you can integrate it yourself it that is easier.

**Comment by mbanon** [comment]
@kirefu 
I already added the `--score_only` flag  to the 0.12 branch :)
I also added a changelog (https://github.com/bitextor/bicleaner/blob/master/CHANGELOG.md)
Please note that I did not add the "if only two columns, first is src and second is trg" thing, please use "--scol 1 --tcol 2" instead. 
Thanks!

**Comment by mbanon** [comment]
And now in the correct branch: https://github.com/bitextor/bicleaner/blob/bicleaner-0.12/CHANGELOG.md hehe

**Comment by kirefu** [comment]
Thanks, yes --scol and --tcol sounds like a better idea

**Pull request closed without merging**
